### PR TITLE
Fix Date related bugs

### LINKED ISSUE #146: [PE-D] View appointment by date
From the UG, `The specified DATE must be in the future.`

`view d/29-oct-2020` does not give a warning that it is in the past: Perhaps consider giving some sort of indication to the user.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chunyongg/ped#4

### LINKED ISSUE #168: [PE-D] Wrong error message
Should warn about empty input instead of wrong date format, same for the `avail` feature

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: raythx98/ped#7

### PR DESCRIPTION
**Pull request by WadeForward**
Fixed bugs for not reporting past date when using view feature with past date
Corrected error message when using view feature with empty date.

Related test case is also added.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/DateParserUtil.java [hunk 1]
```diff
@@ -29,6 +29,8 @@
             + "Please visit our user guide"
             + " for more date/time variants."
             + "\nType help in the input box for the link!";
+    public static final String MESSAGE_EMPTY_DATE = "The Date input should not be empty.\n"
+            + "See the date input format on our User Guide";
```
Comment (xz0127) [inline src/main/java/seedu/address/logic/parser/DateParserUtil.java]: Should we give a sample input here? I think either way would be fine. Let me know what do you think. 👍

**Review by xz0127 — COMMENTED** [review]
Other than the small comment, the rest LGTM! 👍

File: src/main/java/seedu/address/logic/parser/DateParserUtil.java (hunk 1 above)
Comment (WadeForward) [reply src/main/java/seedu/address/logic/parser/DateParserUtil.java]: I don't think we need to give an example here since we are reminding the user to enter a date, it is not that they don't know how to enter the date.

How do the rest think?

File: src/main/java/seedu/address/logic/parser/ViewCommandParser.java [hunk 2]
```diff
@@ -36,6 +38,11 @@ public ViewCommand parse(String arg) throws ParseException {
         }
 
         Date date = ParserUtil.parseDate(argMultimap.getValue(PREFIX_DATE).get());
+
+        if (DateTimeUtil.isExpiredByDay(date.getDate())) {
+            throw new ParseException(MESSAGE_EXPIRED_DATE);
+        }
```
Comment (JinHao-L) [inline src/main/java/seedu/address/logic/parser/ViewCommandParser.java:44]: Would it be better to give a more direct message rather than a generic one? (Since this msg is only used once) 

Maybe we can use: "Cannot view appointments from the past. Past appointments are archived and can be accessed from the archive folder" ?

Let me know what you think! 😄

**Review by JinHao-L — APPROVED** [review]
Other than the comment mentioned, the rest LGTM! 👍
