### PR TITLE
Fix time bugs

### LINKED ISSUE #169: [PE-D] Wrong error message
Similar to #7, 
for d/ t/ and dur/ and most other fields

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: raythx98/ped#8

### PR DESCRIPTION
**Pull request by WadeForward**
Corrected the error message for time parser when an empty string of time in parsed.
Corrected the respective tests

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/TimeParserUtil.java [hunk 1]
```diff
@@ -65,6 +70,10 @@
     public static LocalTime parse(String timeString) throws ParseException {
         requireNonNull(timeString);
 
+        if (timeString.trim().equals("")) {
+            throw new ParseException(MESSAGE_EMPTY_TIME);
+        }
+
```
Comment (JinHao-L) [inline src/main/java/seedu/address/logic/parser/TimeParserUtil.java]: Just some Java trivia.  
You can also take a look at the isBlank() method for String. It returns true if the string is empty or only contain trailing whitespaces. 😄

**Review by JinHao-L — APPROVED** [review]
LGTM! 👍

File: src/main/java/seedu/address/logic/parser/TimeParserUtil.java (hunk 1 above)
Comment (WadeForward) [reply src/main/java/seedu/address/logic/parser/TimeParserUtil.java]: thanks for the advice!
