### PR TITLE
Fix mock pe bugs

### LINKED ISSUE #144: [PE-D] Remark length
Adding a remark through the `remark PATIENT_INDEX [r/REMARK]` command: I believe the limit is 200 words, not too sure whether it is inclusive or exclusive, but I used the following lines of words. On MSWords, it told me that there are 199 words.

The following does not work. I get the message 

```
Each remark has a capacity of up to 200 words and can take all alphanumeric and symbol characters.
Only use a blank remark to delete an existing remark from the patient.
Existing remarks for the patient will also be overridden with the new input.
````

```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the.

```
But this works (198 words in MSWords)

```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.


```

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chunyongg/ped#2

### LINKED ISSUE #151: [PE-D] NRIC format error message could be better
According to the error message as shown, the NRIC I've used should be accepted. Error message is kind of a bit off.

Consider simply saying that `NRIC/FIN input is not a valid *if you want: explanation on format, what number should start etc*`

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: LinkedInk/ped#3

### LINKED ISSUE #170: [PE-D] Appointment which is done can be rescheduled
Does not make sense for appointments that are marked done to be able to be rescheduled? If this is intended, should be documented.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: raythx98/ped#9

### LINKED ISSUE #171: [PE-D] Change feature gives wrong intended outcome upon invalid entry
duration of 2400 gives unchecked exception

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: raythx98/ped#10

### PR DESCRIPTION
**Pull request by Avalionnet**
- Remove remark word limit.
- Improve error message for Nric formatting.
- Fix change command error that allows completed appointments from being rescheduled.
- Fix some unchecked exceptions.

fix #144 , fix #151 , fix #170 and fix #171

### CODE REVIEW

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 1]
```diff
@@ -14,7 +14,7 @@
             + "Past appointments are archived and can be accessed from the archive folder.";
     public static final String MESSAGE_EXPIRED_DATE_TIME = "The appointment date and time should be an upcoming one.";
     public static final String MESSAGE_INVALID_APPOINTMENT_DISPLAYED_INDEX = "The appointment index provided is "
-            + "invalid";
+            + "invalid or missing";
```
Comment (JinHao-L) [inline src/main/java/seedu/address/commons/core/Messages.java]: Hmmm, I don't think this should be edited. An invalid command format message shd be shown if the index is missing.

I took a look at the current code in `ChangeCommandParser` and I think that the message for line 42 (throw ParseException) should be `MESSAGE_INVALID_COMMAND_FORMAT` instead of `MESSAGE_INVALID_APPOINTMENT_DISPLAYED_INDEX`.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -28,9 +28,12 @@
  * Contains utility methods used for parsing strings in the various *Parser classes.
  */
 public class ParserUtil {
+    public static final int MIN_DURATION = 10;
+    public static final int MAX_DURATION = 840;
```
Comment (JinHao-L) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Do you think it would be good to add a comment on top to explain the numbers? or it's quite self-explanatory

**Review by JinHao-L — COMMENTED** [review]
Other than the comments mentioned, the rest LGTM 👍

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 2 above)
Comment (WadeForward) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: I agree with Jinhao about this point 😄

**Review by WadeForward — COMMENTED** [review]
LGTM👍

**Review by JinHao-L — APPROVED** [review]
LGTM 👍
