### PR TITLE
Fix duration bugs

### LINKED ISSUE #167: [PE-D] Appointment for 1800 minutes allowed
Appointment for 1800 minutes allowed. This means the appointment spans across closing hours and last over a day...? Even if allowed, the appointment should be till the next day

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: raythx98/ped#6

### LINKED ISSUE #169: [PE-D] Wrong error message
Similar to #7, 
for d/ t/ and dur/ and most other fields

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: raythx98/ped#8

### PR DESCRIPTION
**Pull request by WadeForward**
Correct wrong message when the duration input is empty.
Fix Duration to reject excess numerical values.

Related Tests added

### CODE REVIEW

**Review by YangYue128-helen — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/parser/AssignCommandParser.java [hunk 1]
```diff
@@ -64,12 +65,18 @@ public AssignCommand parse(String arg) throws ParseException {
...
         LocalTime timeWithLeeway = time.getTime().plusMinutes(CREATION_OFFSET_MINUTES);
         if (DateTimeUtil.isExpired(date.getDate(), timeWithLeeway)) {
             throw new ParseException(MESSAGE_EXPIRED_DATE_TIME);
         }
 
+        // check if the duration exceeds the CLOSING_TIME
+        Duration maxDuration = Duration.between(time.getTime(), CLOSING_TIME);
+        if (duration.compareTo(maxDuration) > 0) {
+            throw new ParseException(Time.MESSAGE_CONSTRAINTS);
+        }
```
Comment (JinHao-L) [inline src/main/java/seedu/address/logic/parser/AssignCommandParser.java]: Maybe it would be better if the check is done in `ParserUtil.parseDuration` instead? This way the check will apply to `ChangeCommandParser` too. (Can just compare the duration with `CLOSING_TIME - OPENING_TIME`)

Lemme know what you think about it?

**Review by JinHao-L — COMMENTED** [review]
Other than the comment mentioned, the rest LGTM 👍

File: src/main/java/seedu/address/logic/parser/AssignCommandParser.java (hunk 1 above)
Comment (WadeForward) [reply src/main/java/seedu/address/logic/parser/AssignCommandParser.java]: if using the `CLOSING_TIME - OPENING_TIME`, there will not be a `ParserException` if the user enters something smaller than the limit but still out of operation hour, since this will only give an error for ending time is before start time in the appointment that cannot be viewed in jar.

Comment (JinHao-L) [reply src/main/java/seedu/address/logic/parser/AssignCommandParser.java]: Hmm, true. Then I guess this will work 👍

Comment (WadeForward) [reply src/main/java/seedu/address/logic/parser/AssignCommandParser.java]: so I just keep it and change the `ChangCommand` also?
